### ISSUE TITLE
The size of tensor a (360) must match the size of tensor b (361) at non-singleton dimension 3

### ISSUE THREAD

**Issue by flybiubiu** [xiezw5/Component-Divide-and-Conquer-for-Real-World-Image-Super-Resolution#12] opened 2021-02-27 14:22 UTC
Thx author! This is a nice project!  

File "./modules/HourGlassSR/model.py", line 132, in forward
    return self.res_block(x + res)
RuntimeError: The size of tensor a (360) must match the size of tensor b (361) at non-singleton dimension 3
My data struct:
<img width="293" alt="Screen Shot 2021-02-27 at 10 18 33 PM" src="https://user-images.githubusercontent.com/20927755/109389947-bddec980-7949-11eb-86ac-93a6d1bb59ca.png">
parser.add_argument('--dataroot', type=str, default='/home/ubuntu/Desktop/data120/DRealSR/x4/Train_x4')
parser.add_argument('--test_dataroot', type=str, default='/home/ubuntu/Desktop/data120/DRealSR/x4/Test_x4')

**Comment by kristingwang** [comment] 2021-02-27 16:22
the same issue

**Comment by xiezw5** [comment] 2021-02-28 14:49
This problem is caused by the TopDown and BottomUp blocks when processing an image with odd length and width. In our settings, the length and width of input images should be multiples of 16. Actually it is a flaw which should be fixed.

**Comment by flybiubiu** [comment] 2021-02-28 14:50
> This problem is caused by the TopDown and BottomUp blocks when processing an image with odd length and width. In our settings, the length and width of input images should be multiples of 16. Actually it is a flaw which should be fixed.

So, Can you fixed this problem??? Thx again!

**Comment by xiezw5** [comment] 2021-02-28 14:54
> > This problem is caused by the TopDown and BottomUp blocks when processing an image with odd length and width. In our settings, the length and width of input images should be multiples of 16. Actually it is a flaw which should be fixed.
> 
> So, Can you fixed this problem??? Thx again!

You can temporarily crop the input images to the appropriate length and width

**Comment by flybiubiu** [comment] 2021-02-28 14:56
> > > 当处理长度和宽度奇数的图像时，此问题是由TopDown和BottomUp块引起的。在我们的设置中，输入图像的长度和宽度应为16的倍数。实际上，这是一个缺陷，应予以修复。
> > 
> > 
> > 所以，您能解决这个问题吗？？？再次感谢！
> 
> 您可以将输入图像临时裁剪为适当的长度和宽度

Thx! I will try it! Thx again!

**Comment by flybiubiu** [comment] 2021-02-28 15:02
Get it !Thx author!I will try it!
ps:
1.Can I change a chat tool(wechat  or so on)?

xiezw5 <notifications@github.com> 于2021年2月28日周日 下午10:54写道：

**Closed as completed** 2021-02-28 17:04 UTC
